name: Build
on:
  push:
    branches: [ '*' ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        program:
        - ares
        platform:
        - name: macos
          os: macos-13
          compiler: clang++
          shell: sh
    name: ${{ matrix.program }}-${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Install macOS Dependencies
      if: runner.os == 'macOS'
      run: |
        brew install make ninja sdl2
        pip install --no-input setuptools
        echo "MAKE=gmake" >> $GITHUB_ENV
    - name: Set up MSVC environment
      if: matrix.platform.msvc-arch != ''
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.platform.msvc-arch }}
    - name: Make
      run: ${MAKE:-make} -C desktop-ui arch=arm64 lto=false build=release cores=cv vulkan=false local=false compiler="${{ matrix.platform.compiler }}" windres="${{ matrix.platform.windres }}"
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.program }}-${{ matrix.platform.name }}
        path: desktop-ui/out/*

     
  release:
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs:
    - build
    steps:
    - uses: actions/checkout@v2
      with:
        path: 'src'
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        path: 'bin'
    - name: Package Artifacts
      run: |
        set -eu
        case ${GITHUB_REF} in
          refs/tags/*) suffix="-${GITHUB_REF#refs/tags/}" ;;
          refs/heads/master) suffix="-nightly" ;;
          *) suffix="" ;;
        esac

        srcdir="${GITHUB_WORKSPACE}/src"
        bindir="${GITHUB_WORKSPACE}/bin"

        # Hack: Workaround for GitHub artifacts losing attributes.
        chmod +x ${bindir}/ares-macos/ares.app/Contents/MacOS/ares

        for package in windows windows-msvc-arm64 macos
        do
          mkdir "${package}"
          cd "${package}"

          # Package ares.
          outdir=ares${suffix}
          mkdir ${outdir}
          cp -ar ${bindir}/ares-${package}/* ${outdir}
          zip -r ../ares-${package}.zip ${outdir}

          cd -
        done
    - name: Create Release
      id: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -eu
        github_rest()
        {
          local method="${1}"
          local url="https://api.github.com${2}"
          shift 2
          >&2 echo "${method} ${url}"
          curl \
            --fail \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            -X "${method}" \
            "${url}" \
            "$@"
        }
        github_get_release_id_for_tag()
        {
          payload=$(github_rest GET "/repos/${GITHUB_REPOSITORY}/releases/tags/${1}") || return
          echo "${payload}" | jq .id
        }
        github_delete_release_by_id()
        {
          github_rest DELETE "/repos/${GITHUB_REPOSITORY}/releases/${1}"
        }
        github_create_release()
        {
          local payload="{
            \"tag_name\": \"${1}\",
            \"target_commitish\": \"${2}\",
            \"name\": \"${3}\",
            \"body\": \"${4}\",
            \"draft\": ${5},
            \"prerelease\": ${6}
          }"
          github_rest POST "/repos/${GITHUB_REPOSITORY}/releases" -d "${payload}"
        }
        make_nightly_release()
        {
          github_create_release \
            nightly \
            "${GITHUB_SHA}" \
            "ares nightly $(date +"%Y-%m-%d")" \
            "Auto-generated nightly release on $(date -u +"%Y-%m-%d %T %Z")" \
            false \
            true
        }
        make_version_release()
        {
          github_create_release \
            "${1}" \
            "${GITHUB_SHA}" \
            "ares ${1}" \
            "This is ares ${1}, released on $(date +"%Y-%m-%d")." \
            false \
            false
        }
        case ${GITHUB_REF} in
          refs/tags/*)
            # Create a new version release using the current revision.
            echo "UPLOAD_URL=$(make_version_release ${GITHUB_REF#refs/tags/} | jq -r .upload_url)" >> $GITHUB_ENV
            ;;
          refs/heads/master)
            # Check for an existing nightly release.
            { release_id=$(github_get_release_id_for_tag nightly); status=$?; } || true
            # Delete existing nightly release if it exists.
            case ${status} in
              0) github_delete_release_by_id "${release_id}" ;;
              22) >&2 echo "No current nightly release; skipping tag deletion." ;;
              *) >&2 echo "API call failed unexpectedly." && exit 1 ;;
            esac
            # Create a new nightly release using the current revision.
            echo "UPLOAD_URL=$(make_nightly_release | jq -r .upload_url)" >> $GITHUB_ENV
            ;;
        esac
    - name: Upload ares-windows
      uses: actions/upload-release-asset@v1
      env: { GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}' }
      with: { upload_url: '${{ env.UPLOAD_URL }}', asset_path: 'ares-windows.zip', asset_name: 'ares-windows.zip', asset_content_type: 'application/zip' }
    - name: Upload ares-windows-msvc-arm64
      uses: actions/upload-release-asset@v1
      env: { GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}' }
      with: { upload_url: '${{ env.UPLOAD_URL }}', asset_path: 'ares-windows-msvc-arm64.zip', asset_name: 'ares-windows-msvc-arm64.zip', asset_content_type: 'application/zip' }      
    - name: Upload ares-macos
      uses: actions/upload-release-asset@v1
      env: { GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}' }
      with: { upload_url: '${{ env.UPLOAD_URL }}', asset_path: 'ares-macos.zip', asset_name: 'ares-macos.zip', asset_content_type: 'application/zip' }
#  - name: Upload ares-ubuntu
#      uses: actions/upload-release-asset@v1
#      env: { GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}' }
#      with: { upload_url: '${{ env.UPLOAD_URL }}', asset_path: 'ares-ubuntu.zip', asset_name: 'ares-ubuntu.zip', asset_content_type: 'application/zip' }

